FROM python:3.9-slim

COPY requirements.txt .
RUN apt-get update
RUN apt-get install make

ARG USERNAME=vorph
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd -g $USER_GID -o $USERNAME
RUN useradd -m -u $USER_UID -g $USER_GID -o -s /bin/bash $USERNAME

USER $USERNAME

ENV PATH "$PATH:/home/${USERNAME}/.local/bin"

RUN /bin/bash -c "pip install -r requirements.txt"

# 8001 for mkdocs
EXPOSE 8001
