FROM python:3.9-slim

RUN apt-get update && apt-get install make -y --no-install-recommends


ARG USERNAME=vorph
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd -g $USER_GID -o $USERNAME
RUN useradd -m -u $USER_UID -g $USER_GID -o -s /bin/bash $USERNAME

USER $USERNAME

COPY requirements.txt .

ENV PATH "$PATH:/home/${USERNAME}/.local/bin"
RUN python -m pip install --upgrade pip && /bin/bash -c "pip install -r requirements.txt"

# 8001 for mkdocs
EXPOSE 8001
