site_name: Helloworld mkdocs
site_author: Mathieu Klimczak
dev_addr: "127.0.0.1:8001"
# repo_url: https://gitlab.internal.citc-eurarfid.com/common/helloworld-mkdocs
# repo_name: common/helloworld-mkdocs
theme:
  name: material
  logo: images/noun_Robot_1955251.svg
  icon:
    repo: fontawesome/brands/gitlab
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer en mode sombre
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Basculer en mode clair

plugins:
  - search:
      lang: fr

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md
  - Section 1:
      - Subsection 1.1:
          - Subsubsection 1.1.1: ssection11/sssection111.md
          - Subsubsection 1.1.2: ssection11/sssection112.md
      - Subsection 1.2:
          - Subsubsection 1.2.1: ssection12/sssection121.md
  - Section 2:
      - Subsection 2.1:
          - Subsubsection 2.1.1: ssection21/sssection211.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.betterem:
      smart_enable: all
  # config pour latex
  - pymdownx.arithmatex:
      generic: true

# config pour latex
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
